const express = require('express');
const Alert = require('../models/Alert');
const logger = require('../config/logger');

const router = express.Router();

const demoAlerts = [
  {
    _id: 'a1',
    title: 'Multiple failed admin logins',
    severity: 'high',
    status: 'open',
    source: 'auth-server-01',
    description: 'Several login failures identified from same IP range',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'a2',
    title: 'Suspicious outbound traffic spike',
    severity: 'critical',
    status: 'investigating',
    source: 'fw-core-01',
    description: 'Traffic spike observed outside baseline threshold',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'a3',
    title: 'Endpoint malware signature hit',
    severity: 'medium',
    status: 'resolved',
    source: 'endpoint-24',
    description: 'Malware signature matched on endpoint-24',
    createdAt: new Date().toISOString()
  }
];

router.get('/', async (req, res) => {
  try {
    const alerts = await Alert.find().sort({ createdAt: -1 }).lean();
    return res.json({ success: true, count: alerts.length, data: alerts });
  } catch (error) {
    logger.warn(`Falling back to demo alerts: ${error.message}`);
    return res.json({ success: true, count: demoAlerts.length, data: demoAlerts });
  }
});

router.post('/', async (req, res) => {
  try {
    const alert = new Alert({
      title: req.body.title || 'Security alert',
      severity: req.body.severity || 'medium',
      status: req.body.status || 'open',
      source: req.body.source || 'unknown',
      description: req.body.description || 'Alert generated by detection rules'
    });

    const saved = await alert.save();
    req.io.emit('new-alert', saved);

    logger.info(`New alert created: ${saved.title}`);
    return res.status(201).json({ success: true, data: saved });
  } catch (error) {
    logger.error(`Alert creation failed: ${error.message}`);
    return res.status(500).json({ success: false, message: 'Failed to create alert' });
  }
});

module.exports = router;
